### PR TITLE
Add Mainnet Seed(mona.seed.fujishan.jp)

### PR DESCRIPTION
**Pull request by fujiwaraizuho**
私が運用しているMainnnetのDNS Seedを追加しました。

### CODE REVIEW

**Comment by wakiyamap** [comment]
LGTM
But, can you add IPv6 addresses ?

**Comment by fujiwaraizuho** [comment]
Support IPv6 address！

**Comment by wakiyamap** [comment]
@fujiwaraizuho great!!

**Review by wakiyamap — APPROVED** [review]

**Comment by cryptcoin-junkey** [comment]
@fujiwaraizuho Thank you for your suggestion. But It's gonna be hard to make a decision to me.
IMO, DNS seeds is a necessary evil. It should be minimum.
And as you know, we have two DNS seeds run by another persons already. I suppose it's enough redundant (for now).

**Comment by cryptcoin-junkey** [comment]
The document will give us some helps.  https://github.com/monacoinproject/monacoin/blob/master-0.17/doc/dnsseed-policy.md

@fujiwaraizuho I believe you are a active developer. Next. Do you believe you must be a DNSseed operator?

**Comment by fujiwaraizuho** [comment]
@cryptcoin-junkey
I don't think there is enough redundancy True, DNS seeds pose a risk to the network, but are what monacoind needs to connect to the network. 
Currently, DNS Seed is run by @tcejorpniocanom and @wakiyamap, but only one operator is open to the community. 
This PR was released 8 days ago, but @tcejorpniocanom is not participating in the discussion.
I must agree to Monacoin's DNS policy and be a DNS seed operator.

**Comment by cryptcoin-junkey** [comment]
@fujiwaraizuho You may know Hodoyoshi-reliability engineering. There is a reasonable cost-merit point on every system. The network of Monacoin nodes also.
AFAIK, two DNS seeds are working fine now. My opinion is "Don't touch anything that goes well."

**Comment by fujiwaraizuho** [comment]
@cryptcoin-junkey
Currently registered DNS Seeds support IPv6 only for DNS seeds operated by @wakiyamap.
When IPv4 is exhausted and IPv6 becomes widespread and IPv6 access to DNS Seed increases, we think that one DNS Seed is not redundant.

**Comment by wakiyamap** [comment]
I will run dnsseed as long as I can do my best.
But I can't deny that Mr.Watanabe and my dnsseed could be down at the same time.
It is my opinion that "more choices are better".

**Comment by cryptcoin-junkey** [comment]
@fujiwaraizuho Surely someday IPv4 will be dead. But when? Tomorrow? In this year? 

@wakiyamap Okay it's enough possible two DNS seeds are down at the same time.
Then, why can we expect mona.seed.fujishan.jp is up?

We must do a optimal design if we want to get redundancy.

**Comment by cryptcoin-junkey** [comment]
As everybody knows, all reviewers on this PR can merge this PR.

Just I exposed my thoughts because it is a kind of Dev's duty.
Obviously, it's not "justice". Just my opinion.

Reviewers can push "Merge pull request" button always.

And, it's also just my additional opinion.
How about shortly (~ a year?) suspending to merge this PR ?

I have no strong objection that the new DNS seed runs with Monad.
(Strictly, I can say no objection as I'm not a dev of Monad. :-) 
And this PR will be acceptable there since the code owner of Monad @wakiyamap approved this PR.

**Comment by wakiyamap** [comment]
For monad(neutrino), it is necessary to connect to the node having compactfilter.
So if there is not much dnsseed, it may not be possible to connect to the monad(neutrino) node.
But we may not have to rush about monacoind.

**Comment by wakiyamap** [comment]
I close it once.
We decide in the next version.

**Comment by wakiyamap** [comment]
@fujiwaraizuho I use it for monad. Thanks!!

**Pull request closed without merging**
