### PR TITLE
[backport]Fix build failure on Ubuntu Hirsute

### LINKED ISSUE #79: Failed to build on Ubuntu Hirsute 21.04
I tried to build Monacoin on Ubuntu Hirsute 21.04 (PPA), but I got the following error.

```
g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../src/config   -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I.  -DBOOST_SP_USE_STD_ATOMIC -DBOOST_AC_USE_STD_ATOMIC -pthread -I/usr/include -I./leveldb/include -I./leveldb/helpers/memenv   -I./secp256k1/include -I./univalue/include   -pthread -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS  -Wstack-protector -fstack-protector-all -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter -Wno-implicit-fallthrough    -fPIE -g -O2 -MT libbitcoin_server_a-httpserver.o -MD -MP -MF .deps/libbitcoin_server_a-httpserver.Tpo -c -o libbitcoin_server_a-httpserver.o `test -f 'httpserver.cpp' || echo './'`httpserver.cpp
In file included from /usr/include/boost/smart_ptr/detail/sp_thread_sleep.hpp:22,
                 from /usr/include/boost/smart_ptr/detail/yield_k.hpp:23,
                 from /usr/include/boost/smart_ptr/detail/spinlock_std_atomic.hpp:18,
                 from /usr/include/boost/smart_ptr/detail/spinlock.hpp:36,
                 from /usr/include/boost/smart_ptr/detail/spinlock_pool.hpp:25,
                 from /usr/include/boost/smart_ptr/shared_ptr.hpp:29,
                 from /usr/include/boost/shared_ptr.hpp:17,
                 from /usr/include/boost/signals2/signal.hpp:21,
                 from ./util.h:34,
                 from httpserver.cpp:9:
/usr/include/boost/function_output_iterator.hpp:14:1: note: ‘#pragma message: This header is deprecated. Use <boost/iterator/function_output_iterator.hpp> instead.’
   14 | BOOST_HEADER_DEPRECATED("<boost/iterator/function_output_iterator.hpp>")
      | ^~~~~~~~~~~~~~~~~~~~~~~
httpserver.cpp:74:10: error: ‘deque’ in namespace ‘std’ does not name a template type
   74 |     std::deque<std::unique_ptr<WorkItem>> queue;
      |          ^~~~~
httpserver.cpp:33:1: note: ‘std::deque’ is defined in header ‘<deque>’; did you forget to ‘#include <deque>’?
   32 | #include <support/events.h>
  +++ |+#include <deque>
   33 | 
httpserver.cpp: In member function ‘bool WorkQueue<WorkItem>::Enqueue(WorkItem*)’:
httpserver.cpp:92:13: error: ‘queue’ was not declared in this scope; did you mean ‘Enqueue’?
   92 |         if (queue.size() >= maxDepth) {
      |             ^~~~~
      |             Enqueue
httpserver.cpp:95:9: error: ‘queue’ was not declared in this scope; did you mean ‘Enqueue’?
   95 |         queue.emplace_back(std::unique_ptr<WorkItem>(item));
      |         ^~~~~
      |         Enqueue
httpserver.cpp: In member function ‘void WorkQueue<WorkItem>::Run()’:
httpserver.cpp:106:35: error: ‘queue’ was not declared in this scope; did you mean ‘Enqueue’?
  106 |                 while (running && queue.empty())
      |                                   ^~~~~
      |                                   Enqueue
httpserver.cpp:110:31: error: ‘queue’ was not declared in this scope; did you mean ‘Enqueue’?
  110 |                 i = std::move(queue.front());
      |                               ^~~~~
      |                               Enqueue
```

The complete build log can be found at [here](https://launchpad.net/~visvirial/+archive/ubuntu/monacoin/+build/20939623).

The error message says the std::deque is declared in &lt;deque&gt;, but this header file is not included in the source file.
It can be solved by just adding the "#include &lt;deque&gt;" directive.

This issue is also reported in the Litecoin repo https://github.com/litecoin-project/litecoin/issues/632 and was solved by the PR https://github.com/litecoin-project/litecoin/pull/643.

(In addition to this, the repo is not maintained for more than two years.
You should catch up to the upstream repo, or may cause a significant security defect.)

### PR DESCRIPTION
**Pull request by wakiyamap**
Fix https://github.com/monacoinproject/monacoin/issues/79

### CODE REVIEW

**Comment by wakiyamap** [comment]
As far as I tested it was fine.

**Comment by wakiyamap** [comment]
@cryptcoin-junkey @tcejorpniocanom 
I asked for a review, but if you are busy, I will test it again and merge it.
I will test it too. If there's a problem, Please reply by Feb. 13(UTC).


P.S. No cat carcasses will be included in this pull request.

**Comment by cryptcoin-junkey** [comment]
@wakiyamap Let me make sure. Can we build binaries on older versions of Ubuntu after merged this PR?

**Comment by wakiyamap** [comment]
@cryptcoin-junkey I have confirmed this in ubuntu 18.04. But after reading this, I realized I haven't tried debian, so I'll check.

**Comment by wakiyamap** [comment]
I've confirmed the build for Ubuntu16.04 and debian9.

**Review by cryptcoin-junkey — APPROVED** [review]
I checked on Debian 10. LGTM.

**Pull request merged**
