### PR TITLE
gitian-build for monacoin

### PR DESCRIPTION
**Pull request by wakiyamap**
~``Don't merge yet.``~

I use this script`contrib/gitian-build.py` here.
https://github.com/wakiyamap/gitian.sigs.mona

I merge it if gitian-sig of v0.17.2 is OK.

### CODE REVIEW

**Comment by yamada-guro-baru** [comment]
I think the result is almost the same.
I use Ubuntu20.04.
I don't think it's a problem.

https://github.com/yamada-guro-baru/gitian.sigs.mona/commit/972d0dcfd87b6b834261a7a13126f3f7971a51e9
my key
```
-----BEGIN PGP PUBLIC KEY BLOCK-----

mJMEYETPuBMFK4EEACMEIwQAZLEPWlHybhaMVN+/1QxVWAXmsOeOhZKLCB/5OO1P
JVFGg1PHBe8HakqDOsUrtWSNZhv/kLOdnxxgTFYetWxuuL0AAj6tNyTmGYSfhkHB
CA8p4tSRrEIfXZJljrTgb9QPD726uzPMKTMcp5yx/+zVUGR6nP7i3Gtxqte6LBrd
jdvZG/i0MnlhbWFkYS1ndXJvLWJhcnUgPHlhbWFkYS1ndXJvLWJhcnVAcHJvdG9u
bWFpbC5jb20+iNMEExMKADgWIQTURC3KUBphFjH6UiaHDWJro0XnnwUCYETPuAIb
AwULCQgHAgYVCgkICwIEFgIDAQIeAQIXgAAKCRCHDWJro0Xnn3XwAgigsqSKbUHs
HKt8DH97RtMz7x4hschtvHDAR4oSqlDK1Yh2ixbXkw/JRTkDro6UoTVpERh5cbbN
k7nWpNuDpEDd0gIJAXSCw2Tr6H6hkPc9grhbEJxY1WebLIA41DWE8Y821YDqjk8T
jYXkmY9+uItpChO22r8sBr3VxLxquYwkNlwW5lZeiLgEEBMKAB0WIQQxVSXoEdXl
hvPKwDKcdAvsiXzkmQUCYETUCAAKCRCcdAvsiXzkmVddAgkBxD4oybzJqtebwSkt
J6+DxkrTGZpoUtSZv8PE45OvoKyM5G9G7ozNRq2V2EyZ9jctrQPVKrd6BlcV9Bd+
DnK8WecCCLLL4qd89C8wcVBLpnKSeMaOr/KibOGDv+oPZM0jiGVWLabByk9c7yLS
doKSLro6Ng8vwiLRYNUou9ktiZmM2NYr
=G6q1
-----END PGP PUBLIC KEY BLOCK-----
```

P.S. I recreated it as a binary file.

**Comment by yamada-guro-baru** [comment]
yet?
Is there any reason to stop it?

**Comment by wakiyamap** [comment]
Maybe.
@cryptcoin-junkey is busy at monaparty.
I can't know what @tcejorpniocanom is thinking.
https://twitter.com/tcejorpniocanom/status/1387804359178604544

**Comment by wakiyamap** [comment]
Close the pull request to avoid confusion with the 0.20 commit.
@yamada-guro-baru Thanks.　It would be great if you could help us with the next gitian build.

**Pull request closed without merging**
